<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJNdEO0l\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJNdEO0l/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJNdEO0l.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJNdEO0l\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJNdEO0l\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JNdEO0l',
    'container.build_id' => 'e86068c9',
    'container.build_time' => 1516610727,
));
