<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTuRnLD\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTuRnLD/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQTuRnLD.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQTuRnLD\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQTuRnLD\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QTuRnLD',
    'container.build_id' => '4e175338',
    'container.build_time' => 1515675336,
));
