<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYS0dx3N\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYS0dx3N/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYS0dx3N.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYS0dx3N\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYS0dx3N\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'YS0dx3N',
    'container.build_id' => 'c57e31f1',
    'container.build_time' => 1515676902,
));
